site_name: CodingNomads Mentor Docs
site_description: Information on how to deliver a great mentorship experience.
site_author: Martin Breuss
nav:
  - README: README.md
  - Requirements: 01_requirements.md
  - Onboarding: 02_new_mentors.md
  - Mentorship: 03_mentorship_process.md
  - Labs & Projects: 04_code_labs.md
  - Philosophy: 04_how_to_mentor.md
  - Tools: 05_tools.md
  - Community: 06_community.md
  - Payment: 07_payment.md
  - Checklist: 08_checklist.md
  - FAQs: 09_faq.md
  - Feedback: 10_feedback.md
  - Bookmarks: 11_bookmarks.md
  - Templates: 12_templates.md
  - Student Notes: 13_student_notes.md
  - Practical Tips: 14_tips.md
  - StayAtHome FAQ: 15_home_faq.md
  - Code Of Conduct: 16_code_of_conduct.md
theme:
  name: readthedocs
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s
markdown_extensions:
  - toc:
      permalink: True
repo_url: https://github.com/CodingNomads/mentor-docs
repo_name: GitHub
